spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: reserva
          uri: lb://RESERVA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/reserva/**
        - id: disponibilidade
          uri: lb://DISPONIBILIDADE-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/disponibilidade/**

eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka

server:
  port: 9098
